### ISSUE TITLE
physical wrap / unwrap text

### ISSUE THREAD

**Issue by aplsimple** [phase1geo/TextShine#1]
Hi Trevor,

Would you consider two features for TextShine: "physical wrap / unwrap"? I mean the following:

We have a text like:

    1## 2#### 3##### 4######
       5# 6# 7# 8##### 9#

where N# are words indexed.

We like to have, say, a text of 10 characters width. We apply "physical wrapping" to the text, thus resulting in:

    1## 2#### 
    3##### 4##
    ####
       5# 6# 7#
    8##### 9#

And vice versa, if we need to return to the original (unwrapped) text, we apply the  "physical wrapping".

The task isn't so simple as it seems, because you should take into account the indenting, paragraphs, empty lines, cutting words etc. (even possibly the grammar with i18n).

---

Where this features may be useful? E.g. you've got a text wrapped physically and you want to view it in a frame wrapping the text in its turn - then you'll see the text somewhat distorted: "physical" ends of lines would be added to the frame's ones. But applying "physical unwrap" you'll get the normal text fit for the editing frame.

And vice versa, if you got a text unwrapped and have a viewing frame not providing the wrap feature (e.g. a console) - then you need to apply "physical wrap" to the text, so that you can view it in the unwrapping frame (e.g. having 80 character width).

**Comment by phase1geo** [comment]
That is a great idea. I had thought about this inclusion of this feature previously, so it is good to hear that others would find it useful as well.

**Comment by phase1geo** [comment]
I have this feature essentially coded and will be available in the 1.0.0 release
