### ISSUE TITLE
TEXT Doesnt look good on dark color schemes

### ISSUE THREAD

**Issue by Aneeqasif** [phase1geo/TextShine#16]
![image](https://user-images.githubusercontent.com/78728701/140599866-5aa7eed2-4a7f-4f70-9805-677ed63ee66f.png)

**Comment by phase1geo** [comment]
That's weird. TextShine doesn't do any theming, leaving that up to the system style sheet.

**Comment by phase1geo** [comment]
I have filed an issue with the elementary OS Stylesheet project.  The stylesheet that you are using appears to be different than elementary's.

**Comment by phase1geo** [comment]
After looking into the issue further, I have addressed it in the master branch.
