### ISSUE TITLE
Transformation does not work with special characters like ñ

### ISSUE THREAD

**Issue by Hedronmx** [phase1geo/TextShine#17]
As the title says, i cant convert to uppercase or lowercase when using special characters

**Comment by phase1geo** [comment]
I have implemented a fix in the master branch.  If you could try out that version and let me know if it fixes your issue, I would appreciate that.

**Comment by Hedronmx** [comment]
I get the following error when running ./app run

`(com.github.phase1geo.textshine:5957): GLib-GIO-ERROR **: 11:46:13.603: Settings schema 'com.github.phase1geo.textshine' is not installed
./app: line 44:  5957 Trace/breakpoint trap   ./com.github.phase1geo.textshine "${@:2}"
`

**Comment by phase1geo** [comment]
You could either build/install the Flatpak with './app flatpak' or you will need to install TextShine first './app install' before running.

**Comment by Hedronmx** [comment]
Works perfectly!
