### ISSUE TITLE
[bug] Application freezes on some regular expression input

### ISSUE THREAD

**Issue by Schlaefer** [phase1geo/TextShine#19]
Textshine 1.2.0

Steps to reproduce:

1. Click on the "Regular Expression" action
2. In the _empty_ field for the regular expression of that action enter characters that have special meaning in regex, e.g. "^", "$", ".*"

Observed behavior:

The application immediately stops to respond and goes to 100% CPU.

Expected behavior:

The application shouldn't freeze and allow further input in the regular expression input field.

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.  Good find!
