### ISSUE TITLE
[feature] Add "Remove matched line" action

### ISSUE THREAD

**Issue by Schlaefer** [phase1geo/TextShine#20]
Add a "Remove matched line" action, which should work like "Remove matched text" but removes the whole line of the match.

**Comment by phase1geo** [comment]
I have implemented a new feature in the Find and Regular Expression called "Highlight Line".  When the checkbox is selected, the entire matching line will be highlighted as a match.  The "Remove Matched Text" command can then be used to remove the line itself.  Implementing feature in this way allows the other match-based commands to operate on the line, if the user needs to.
