### ISSUE TITLE
Feature idea: Decode URL action

### ISSUE THREAD

**Issue by artemgur** [phase1geo/TextShine#22]
It would be great to have a reverse action to Encode URL, which would convert encoded URLs to their original form.
It would be useful, for example, because when you copy a URL with non-English characters from browser, it's copied in encoded form, and Decode URL action would be very useful to decode the URL to paste somewhere in much shorter and readable form.

**Comment by phase1geo** [comment]
This feature has been implemented in the master branch.  It will be generally available in the 2.0 release that is coming later today.
