### ISSUE TITLE
Package as Flatpak for elementary OS 6

### ISSUE THREAD

**Issue by danrabbit** [phase1geo/TextShine#9]
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

**Comment by phase1geo** [comment]
Is it safe to use the https://beta.developer.elementary.io website to submit this application?  It currently lacks a Stripe key which is needed to monetize this application.

**Comment by danrabbit** [comment]
@phase1geo The beta dashboard is still a work in progress, but I can set up an import manually for you. Unfortunately, we're not able to generate new stripe keys right now

**Comment by phase1geo** [comment]
Will there be any issues with having you manually import this project without the Stripe key and then later on, when you are able to generate these, have the project get updated with this capability?  Or should I just hold off until the new developer.elementary.io is ready for prime-time?
